  CREATE TABLE "ORCLAPPQA"."ACTIVIDADES_OFCS" 
   (	"FECHA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"RECURSO_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"ACTIVIDAD_ID" NUMBER NOT NULL ENABLE, 
		"PRIORIDAD" NUMBER NOT NULL ENABLE, 
		"STATUS" NUMBER NOT NULL ENABLE, 
		"START_TIME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"END_TIME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"ASSIGNMENT_TIME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"BOOKING_TIME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"DURACION" NUMBER NOT NULL ENABLE, 
		"TIPO" NUMBER NOT NULL ENABLE, 
		"COMENTARIOS" VARCHAR2(500 BYTE), 
		"FECHACREDITOOTORGAMIENTO" VARCHAR2(20 BYTE), 
		"FECHA_POSIBLE_PAGO" VARCHAR2(20 BYTE), 
		"FECHA_VISITA_A_SUCURSAL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"ROUTE_DATE" VARCHAR2(20 BYTE), 
		"SALDOEXIGIBLE" VARCHAR2(50 BYTE), 
		"TOTALPENDIENTE" VARCHAR2(20 BYTE), 
		"TOTALABONADO" VARCHAR2(20 BYTE), 
		"IDSUCURSAL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"STREETADDRESS" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
		"FIRSTMANUALOPERATIONUSER" VARCHAR2(20 BYTE), 
		"TRAVELTIME" VARCHAR2(20 BYTE), 
		"TIMEDELIVEREDEND" VARCHAR2(20 BYTE), 
		"TIMEDELIVEREDSTART" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
		"TIMESLOT" VARCHAR2(20 BYTE), 
		"CUSTOMERNUMBER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
		"APPTNUMBER" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
		"ETIQUETAS" VARCHAR2(300 BYTE), 
		"DICTAMEN" VARCHAR2(40 BYTE), 
		"SUBDICTAMEN" VARCHAR2(50 BYTE), 
		"NUMERO_CREDITO" VARCHAR2(15 BYTE), 
		"NUMERO_SOLICITUD" VARCHAR2(10 BYTE), 
		"NUMERO_CLIENTE" VARCHAR2(20 BYTE), 
		"LUGAR_GESTION" VARCHAR2(20 BYTE), 
		"ETIQUETA" VARCHAR2(60 BYTE), 
		"COORDENADA_X" VARCHAR2(20 BYTE), 
		"COORDENADA_Y" VARCHAR2(20 BYTE)
    )
   TABLESPACE "ORCLAPPQA_DATA_DAT"

   CREATE UNIQUE INDEX ORCLAPPQA.IDX_ACTIVIDADES_PK ON ORCLAPPQA.ACTIVIDADES_OFCS (ACTIVIDAD_ID) TABLESPACE ORCLAPPQA_DATA_IDX NOLOGGIN

   ALTER TABLE ORCLAPPQA.ACTIVIDADES_OFCS ADD (CONSTRAINT ACTIVIDADES_OFCS_PK PRIMARY KEY (ACTIVIDAD_ID) USING INDEX)

   ALTER TABLE ORCLAPPQA.ACTIVIDADES_OFCS ADD (CONSTRAINT PRIORIDAD FOREIGN KEY (PRIORIDAD) REFERENCES ORCLAPPQA.CAT_ACTIVIDAD_PRIORIDAD (PRIORIDAD_ID))

   ALTER TABLE ORCLAPPQA.ACTIVIDADES_OFCS ADD (CONSTRAINT ESTATUS FOREIGN KEY (ESTATUS) REFERENCES ORCLAPPQA.ACTIVIDAD_STATUS_ID (ACTIVIDAD_STATUS_ID))

   ALTER TABLE ORCLAPPQA.ACTIVIDADES_OFCS ADD (CONSTRAINT TIPO FOREIGN KEY (TIPO) REFERENCES ORCLAPPQA.CAT_ACTIVIDAD_TIPO (ACTIVIDAD_TIPO_ID))

   ALTER TABLE ORCLAPPQA.ACTIVIDADES_OFCS ADD (CONSTRAINT ACTIVIDAD_RECURSO_ID_FK FOREIGN KEY (RECURSO_ID) REFERENCES ORCLAPPQA.EJECUTIVO (RECURSO_ID))