CREATE TABLE "ORCLAPPQA"."CAT_SUCURSAL" 
   (	"SUCURSAL_ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
		"SUCURSAL" VARCHAR2(50 BYTE)
   )
   TABLESPACE "ORCLAPPQA_DATA_DAT"

CREATE UNIQUE INDEX ORCLAPPQA.IDX_SUCURSAL_PK ON ORCLAPPQA.CAT_SUCURSAL (SUCURSAL_ID) TABLESPACE ORCLAPPQA_DATA_IDX NOLOGGIN
ALTER TABLE ORCLAPPQA.CAT_SUCURSAL ADD (CONSTRAINT CAT_SUCURSAL_PK PRIMARY KEY (SUCURSAL_ID) USING INDEX)