CREATE TABLE "ORCLAPPQA"."CAT_ACTIVIDAD_TIPO" 
    (	"ACTIVIDAD_TIPO_ID" NUMBER NOT NULL ENABLE, 
		"TIPO" VARCHAR2(20 BYTE) DEFAULT NULL NOT NULL ENABLE
	)
	TABLESPACE "ORCLAPPQA_DATA_DAT"

CREATE UNIQUE INDEX ORCLAPPQA.IDX_ACTIVIDAD_TIPO_PK ON ORCLAPPQA.CAT_ACTIVIDAD_TIPO (ACTIVIDAD_TIPO_ID) TABLESPACE ORCLAPPQA_DATA_IDX NOLOGGIN
ALTER TABLE ORCLAPPQA.CAT_ACTIVIDAD_TIPO ADD (CONSTRAINT CAT_ACTIVIDAD_TIPO_PK PRIMARY KEY (ACTIVIDAD_TIPO_ID) USING INDEX)