CREATE TABLE "ORCLAPPQA"."CAT_ETIQUETA" 
   (	"ETIQUETA" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
		"ETIQUETA_ID" NUMBER NOT NULL ENABLE
	)
   TABLESPACE "ORCLAPPQA_DATA_DAT"

CREATE UNIQUE INDEX ORCLAPPQA.IDX_ETIQUETA_PK ON ORCLAPPQA.CAT_ETIQUETA (ETIQUETA_ID) TABLESPACE ORCLAPPQA_DATA_IDX NOLOGGIN
ALTER TABLE ORCLAPPQA.CAT_ETIQUETA ADD (CONSTRAINT CAT_ETIQUETA_PK PRIMARY KEY (ETIQUETA_ID) USING INDEX)