CREATE TABLE "ORCLAPPQA"."CAT_RESOURCE_STATUS" 
   (	"RECURSO_STATUS_ID" NUMBER, 
		"STATUS" VARCHAR2(20 BYTE) NOT NULL ENABLE
   )
   TABLESPACE "ORCLAPPQA_DATA_DAT"

CREATE UNIQUE INDEX ORCLAPPQA.IDX_RESOURCE_ESTATUS_PK ON ORCLAPPQA.CAT_RESOURCE_STATUS (RECURSO_STATUS_ID) TABLESPACE ORCLAPPQA_DATA_IDX NOLOGGIN
ALTER TABLE ORCLAPPQA.CAT_RESOURCE_STATUS ADD (CONSTRAINT CAT_RESOURCE_STATUS_PK PRIMARY KEY (RECURSO_STATUS_ID) USING INDEX)