CREATE TABLE "ORCLAPPQA"."EJECUTIVO" 
   (	"RECURSO_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
    	"NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    	"PARENT_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
    	"E_MAIL" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
    	"STATUS" NUMBER NOT NULL ENABLE, 
    	"TIPO" NUMBER NOT NULL ENABLE
   )
   TABLESPACE "ORCLAPPQA_DATA_DAT"

CREATE UNIQUE INDEX ORCLAPPQA.IDX_EJECUTIVO_PK ON ORCLAPPQA.EJECUTIVO (RECURSO_ID) TABLESPACE ORCLAPPQA_DATA_IDX NOLOGGIN
ALTER TABLE ORCLAPPQA.EJECUTIVO ADD (CONSTRAINT EJECUTIVO_PK PRIMARY KEY (RECURSO_ID) USING INDEX)